### ISSUE TITLE
Are HTTPS OAuth redirects in Tableau Desktop possible?

### ISSUE THREAD

**Issue by tjbanghart** [tableau/connector-plugin-sdk#1017]
**About You:**
Name: TJ Banghart
Company: Google

**Your question:**
I am attempting to set up a new connector with OAuth but I am unable to use `https://` in the `redirectUrisDesktop` param of the `oauthConfig.xml` file. It seems to get replaced with `http://`. I assume this is by design? Is there any way to override this?

The OAuth server I am attempting to use requires redirect URLs for clients over HTTPS, otherwise the request is rejected. Any advice would be appreciated. Thank you!

**Comment by tjbanghart** [comment]
`oauth-service.log` shows the parsed redirect as being different from what was given:

`com.tableau.baserequestors.BaseOAuthRequestor - The parsed redirect uri is: http://localhost:55556/Callback`

despite being given the following in `oauthConfig.xml`
`<redirectUrisDesktop>https://localhost:55556/Callback</redirectUrisDesktop>`

This is on Tableau Desktop 2021.2 on MacOS

**Comment by jkoskela** [comment]
We don't support https. It would require installing custom certificates in the system trust store, otherwise the user would get warnings about untrusted certs. And it isn't needed or recommended.

https://developers.google.com/identity/protocols/oauth2/native-app#request-parameter-redirect_uri
  | Loopback IP address | http://127.0.0.1:port or http://[::1]:port

https://www.rfc-editor.org/rfc/rfc8252#section-7.3

You might need to enable OAUTH_CAP_SUPPORTS_HTTP_SCHEME_LOOPBACK_REDIRECT_URLS. That will make the final redirect URL be something like http://127.0.0.1:[port]/Callback.

If the auth server doesn't support dynamic port ranges for localhost/loopback, then you should also specify the redirect URLs like you are doing. But leave them referring to localhost, as you have it, we will rewrite them if that capability is enabled...I am cleaning up the docs now. i will also open a bug on the redirect URL confusion. I just learned about that.

Also ensure you have multiple redirectUrisDesktop.
