### ISSUE TITLE
[BUG] Cannot connect using the Denodo JDBC connector when the password of the user contains the symbol "="

### ISSUE THREAD

**Issue by carlossc** [tableau/connector-plugin-sdk#1054]
**Describe the bug**

Cannot connect using the Denodo JDBC connector when the password of the user contains the symbol `=`. We do not know if it happens with other characters.

The password sent to the Denodo JDBC driver is truncated starting with the first occurrence of `=`. For example, if the password is `sample=pass`, the password received by the JDBC driver is `sample`. The connector implementation sends to the driver the password as received by the SDK API:

```props["password"] = attr[connectionHelper.attributePassword];```

It works well if, instead of using the Denodo JDBC connector (based on this SDK), you use the Generic JDBC Connector of Tableau, using the same Denodo JDBC driver.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Tableau Version: Tested with Tableau 2022.3, the latest version of the Tableau Denodo JDBC connector and the latest version of the Denodo JDBC Driver.

**About you:**
 Name: Carlos Santos
 Company: Denodo Technologies. I am reporting this on behalf of a mutual customer (I can provide the name offline). This customer is using the Denodo JDBC connector and they cannot log in to Denodo from Tableau because of this. 
The customer opened a support case with us, we detected this issue and we asked the customer to open a support case as well with Tableau so the issue can be prioritized appropriately.

**Comment by pvanderknyff** [comment]
Hi Carlos,

Looking at your connection-properties script, you're using an old, deprecated version of the API. You return the properties as a vector of strings as "key=value", which as you've seen truncates the values at the first equals sign. The correct way is as an object of these pairs, which was added in 2019.4.1. My guess is that the connector was started off of a really old version of our samples before they were updated to use the newer API.

The solution here is to return props directly, instead of creating formattedProps.

The API is documented here: https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-properties
You can see an example of this pattern in the postgres_jdbc sample: https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/connectionProperties.js

**Comment by carlossc** [comment]
@pvanderknyff Thank you. You can close this. I will pass this to the team that develops our connector.
