### ISSUE TITLE
[Question] question regarding connection-normalizer

### ISSUE THREAD

**Issue by xsgao-github** [tableau/connector-plugin-sdk#1072]
**About You:**
Name: Song Gao
Company: Starburst Data

**Your question:**
Quote from https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-normalizer

> Starting in Tableau 2021.1 a connector using Connection Dialog V2 style, connection-fields, can let the system determine at runtime the correct connection-normalizer by not defining it. Any connection-normalizer defined in the tdr file will take precedence at runtime. To use set min-version-tableau=’2021.1’ or newer in the manifest file.

1. What does "To use" refer to? To use the feature that "let the system determine at runtime the correct connection-normalizer"?
2. Do I have to set `min-version-tableau='2021.1`? I set `min-version-tableau='2020.4` in my `manifest.xml`, and changed the `connection-normalizer` element in my `.tdr` as simple as:

```
<connection-normalizer>
   <required-attributes>
    <attribute-list>
     <attr>dbname</attr>
    </attribute-list>
   </required-attributes>
  </connection-normalizer>
```

And Tableau Desktop 2020.4.24 still works. It figures out required (and optional) fields based on `conection-fields.xml` and `connection-normalizer` element, populates the correct connection element in .twb.

**Comment by rosswbrown** [comment]
This documentation is accurate, but not as complete as it should be. We will take an item to improve this and thanks for raising it. As I can see in #1076 this is causing confusion on what is considered by design versus a bug.

In general this has not been a feature used by our partners developing [Tableau Exchange connectors](https://tableau.github.io/connector-plugin-sdk/docs/gallery-submission).

Regarding question 2, it is required that `min-version-tableau='2021.1` is used with this feature. In scenarios with multiple connections this can be an important distinction.

Regarding question 1, an empty or not present `<connection-normalizer>` element would be required to trigger the system to attempt to generate this list automatically.

This comes with some caveats that certain scenarios are not detected properly, like when `dbname` is required as a part of connection strings, but isn't a [field](https://tableau.github.io/connector-plugin-sdk/docs/mcd#field-1) on the connection dialog.

At this time I would not recommend this approach and continue to define all attributes used with guidance from the other documentation and connector packager warnings.

**Comment by xsgao-github** [comment]
Unfortunately, we need `dbname` in `connectionBuilder.js` to build URL. So I cannot remove `<connection-normalizer>`. It appears to me that Tableau Desktop can override `<connection-normalizer>` by merging field elements defined in `connectionResolver.tdr` and `connection-fields.xml`.

RE #2, would you please explain `In scenarios with multiple connections`? V2 dialog was introduced in 2020.3. Did you mean 	`dynamic normalizer was introduced in 2021.1? But why it works very well in Tableau Desktop 2020.4?

**Comment by rosswbrown** [comment]
Based on above this is not a good fit for your connector's requirements. It does not merge additionally defined `attrs`, but is an all or nothing design currently.

While it may appear to work in Tableau Desktop 2020.4, it is not actually doing anything. The best explanation of the importance of what is happening is the first paragraph of this section of the [connection-normalizer](https://tableau.github.io/connector-plugin-sdk/docs/api-reference#connection-normalizer) documentation.

Until this automatic connection normalizer scenario can be accurately documented it will be removed in the linked PR.
