### ISSUE TITLE
[BUG] Customize error message for data source connection errors

### ISSUE THREAD

**Issue by ArunaBala99** [tableau/connector-plugin-sdk#1077]
VISA has created an in house JDBC driver for one of our db system, and trying to throw error message via a SQLException(String reason) (java.sql.SQLException) for few scenarios. The reason argument that they are passing to the SQLException is getting displayed currently below the default error message of “Unable to proceed …”, which is little misleading for a user. So what they are looking for is to replace the whole error dialog with only the message that they are passing and not with any other extra default messages. 

One more thing is that the reason argument they are passing is HTML, but it gets rendered as text only currently. We need to render the error message as HTML so that we have flexibility of styling the message. They are looking to replace entire content of the message with our jdbc driver’s message

 Name:
![Error Message](https://user-images.githubusercontent.com/125602831/219470517-1bd2c596-e0ab-47fc-95cb-ced33feaac83.png)

Customers: VISA, Mc Donalds

There is also a community post idea request on [here](https://community.tableau.com/s/question/0D54T00000OOx4iSAD/is-it-possible-to-change-the-verbiage-or-error-messages)

**Comment by rosswbrown** [comment]
It is currently considered by design that the driver's error message text is displayed at the bottom of the error dialog, with Tableau's common header and general error messages at the top. 

Tableau relies in part on accurate SQL States returned from the JDBC driver to provide the best general error messages to the user.  If the `SQLException` includes `SQLState` this can potentially change the general error message. See [Important SQLStates](https://tableau.github.io/connector-plugin-sdk/docs/drivers#important-sqlstates) for some additional documentation in this area.
