### ISSUE TITLE
Connector Plugin TDVT Issue.

### ISSUE THREAD

**Issue by gmoin789** [tableau/connector-plugin-sdk#11]
I'm struggling with below error with custom named connector TDVT running some some Test Cases.

"LoadDatasource DataSourceException: Execution of a connector plugin script component exceeded the 3000ms timeout."

I'm using Tableau Main version and TDVT 1.4.4

Can you please help what changes i have to made.

**Comment by lriggs** [comment]
Does the issue persists after a couple of attempts? You can try using your plugin in Tableau Desktop using the same command line argument and see if you can connect to your datasource there.

I have seen this issue very rarely when first running a plugin but it was never reproducible after the first time. Otherwise could the custom javascript have a logical endless loop somewhere?

**Comment by lriggs** [comment]
You might try running with fewer threads. I'm not sure if this will make a difference but it would be an interesting experiment. You can pass '-t 1' to tdvt to use just one thread.
