### ISSUE TITLE
How to use jdbc Driver to connect to dolphindb

### ISSUE THREAD

**Issue by peeyee** [tableau/connector-plugin-sdk#1157]
HI, tableau teams:
    I am trying to use jdbc Driver to connect to [dolphindb](https://www.dolphindb.com) and follow the document([JDBC](https://help.tableau.com/current/pro/desktop/zh-cn/examples_otherdatabases_jdbc.htm)), still there are some problems. 
    
![image](https://github.com/tableau/connector-plugin-sdk/assets/47773420/2b08bfa7-b653-4453-ab6b-92bec25c96a1)
![image](https://github.com/tableau/connector-plugin-sdk/assets/47773420/7c336ebc-0dfc-4da9-9a36-29a748715722)
    Could you give me some help?

**Comment by pvanderknyff** [comment]
Hi,

This is the wrong place to get support on the Other Databases (JDBC) feature. This github page is for the Connector SDK for Tableau. Asking on the [community forums](https://www.community.tableau.com/s/) would be a better bet for this issue, or you can reach out to DolphinDB for specific details on connecting using their driver.

Closing since this is not an SDK question.

**Comment by peeyee** [comment]
Thanks!
