### ISSUE TITLE
New connector name not showing up in the Connectors List

### ISSUE THREAD

**Issue by ross8886** [tableau/connector-plugin-sdk#1191]
**Your question:**

I have a set of code files (manifest.xml, dialect.tdd and other connector files) placed in “C:\Users\USERNAME\Documents\My Tableau Repository\Connectors” folder.

I know that the name specified in manifest.xml file should show in the list of Connectors (Installed Connectors/Additional Connectors) in Tableau Desktop (2022.1.12), but it’s not.
Tried adding the switch -DConnectPluginsPath="C:\Users\a758019\Documents\My Tableau Repository\Connectors" while launching Desktop, still no luck.

Later I downloaded the sample manifest.xml from https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/manifest.xml and replaced it with mine however it still doesn’t show “PostgreSQL JDBC” in the Connectors list.

Please suggest

**Comment by aiguofer** [comment]
I run it with `-DDisableVerifyConnectorPluginSignature=true` as well.

**Comment by ross8886** [comment]
Thank you. I just tried this as well. Still no luck.
Also its just the raw files and not a packaged taco file.

**Comment by aiguofer** [comment]
There's likely an error with one of the files then. You could grep the logs for your connector class name:
```
grep "<your_connector_class_name>" /Users/$USER/Documents/My\ Tableau\ Repository/Logs/log.txt
```

**Comment by pvanderknyff** [comment]
aiguofer is correct, your logs will show the exact reason why the connector is not loading. It's usually a simple XML error that means Tableau can't load the connector, usually easy to fix. 

However, I think I know what the issue is here.

You said the following in your question:

> I have a set of code files (manifest.xml, dialect.tdd and other connector files) placed in “C:\Users\USERNAME\Documents\My Tableau Repository\Connectors” folder.

You've got the command line argument for loading unpcakcaged connectors correct it looks like, otherwise we wouldn't load any unpackaged connectors. However, it's ambiguous to me from the quote if the connector files are placed loose in the Connectors folder, or placed in their own subdirectory. The `DConnectPluginsPath` argument points to the directory containing the directories that contain the connector files. (Docs [here](https://tableau.github.io/connector-plugin-sdk/docs/run-taco#set-up-tableau-desktop))

Confirm that your directory structure looks like this (for the sample connector):
`C:\Users\USERNAME\Documents\My Tableau Repository\Connectors\postgres_jdbc\manifest.xml`
and not this:
`C:\Users\USERNAME\Documents\My Tableau Repository\Connectors\manifest.xml`

Let me know if you still have any questions.
