### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tlinhngo** [tableau/connector-plugin-sdk#1233]
Thanks for filing a bug report! Please check out our docs on [Filing a Bug with the SDK](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts) for guidance on what to include with your report. 

**Describe the bug**
I try to connect aws DocumentDB from Tableau. 
1. Download Document DB JDBC Driver 
2. then install Amazon Document DB Connector on Tableau
3. I put all information to connect Document DB 

but I get this issue [An error occurred while communicating with Amazon DocumentDB by Amazon Web Services
There was a problem while running the connector plugin. Reinstall the plugin or contact the plugin provider.
Note that you might need to make local configuration changes to resolve the error.
Error Code: 14D18B1F
Package signature verification failed during connection creation.
Connector Class: documentdbjdbc, Version: 1.14.0.0]

**Screenshots**
![Screenshot 2024-05-07 at 5 06 43 PM](https://github.com/tableau/connector-plugin-sdk/assets/142457349/e6847ff0-a704-41f6-a791-d33627f7432d)

**Desktop (please complete the following information):**
 - OS: MAC M1
 - Tableau Version : Tableau Desktop 2024.1.2

**About you:**
 Name:
 Company:

**Comment by pvanderknyff** [comment]
The DocumentDB connector is not made by Tableau, it's supported by Amazon. If you're seeing problems with their connector you should be reaching out to them by clicking on the "For Support" link in the error message, which links to here: https://github.com/aws/amazon-documentdb-jdbc-driver/issues.

What happened here is that the signature for the taco file is no longer valid, and Tableau rejects the connector because of it. There is already an issue about this opened on the DocumentDB connector about this issue: https://github.com/aws/amazon-documentdb-jdbc-driver/issues/564

In the meantime, as a workaround, you can use the -DDisableVerifyConnectorPluginSignature=true command line argument to disable signature verification so you can use the connector.

We'll try and reach out to Amazon to get the Exchange listing updated once we have a fixed taco.

Closing this issue because it is not related to the Connector SDK platform, but a third-party connector.
