### ISSUE TITLE
Errors in TDVT

### ISSUE THREAD

**Issue by ari-sqream** [tableau/connector-plugin-sdk#172]
I tun TDVT and have a long section of queries that end with an error -
Tableau was unable to generate a query to perform this operation.

How can I find the details why did that happen?
I am using a .tdd file

**Comment by lriggs** [comment]
“QueryCompilation” with no generated query often means that Tableau was not able to compose a query because of conflicting CAP_ settings or missing dialect functions. One common scenario is if you have both temp tables and subqueries turned off in your capability settings. There are certain tests that generate queries which require one of those. Several different CAP_ settings affect this and we have documented them here:  https://tableau.github.io/connector-plugin-sdk/docs/capabilities
