### ISSUE TITLE
Does a custom TDC cancel all checks?

### ISSUE THREAD

**Issue by traceon** [tableau/connector-plugin-sdk#428]
When writing a custom TDC for an ODBC driver, does Tableau skip all the checks and just use only what  is in TDC?
Looking at workbook file, the list of capabilities consists only of those specified in custom TDC, if one provided. But if there is no TDC, the list of detected capabilities is quite long, and I really would like to make just a few adjustments to otherwise useful auto-detected list.

**Comment by lriggs** [comment]
There are some preset capabilities documented here https://tableau.github.io/connector-plugin-sdk/docs/capabilities if you develop your connector using the SDK. Tableau does a dynamic temp table check to make sure the user has the ability to create a temp table at connection time, but otherwise the settings are static.

If you create a connection using 'Other ODBC' and then save the workbook there will be several dynamically determined capabilities and many others which are simple defaults.

I recommend using the documentation link as a guide and then setting those capabilities in your manifest file.

**Comment by traceon** [comment]
The question is more about the mechanics of how custom TDC values are applied, and does Tableau continue to probe for capabilities after it reads TDC. For example, I see `SQL_DRIVER_VER` (an obvious thing, that you don't want to provide a custom value for) saved in the workbook when no TDC is provided (i.e., in full auto mode), but if I provide a (useful) TDC, this particular `SQL_DRIVER_VER` won't be stored in the workbook anymore.

**Comment by lriggs** [comment]
SQL_DRIVER_VER is only a capability for Other ODBC connections, which we call Generic ODBC.

Those types of connectors dynamically determine many of the capabilities by probing the driver. The settings in the tdc file will apply over those, so they should override anything else.

Also if you look in the saved workbook, the customization section will have 'enabled=false' which indicates the values there are not applied, but just logged.

**Comment by traceon** [comment]
> The settings in the tdc file will apply over those, so they should override anything else.

I see, so is my understanding correct, that I can safely list everything I want to **override** in the TDC, and the rest will still be auto-detected and in effect?

**Comment by sidwray** [comment]
tfs 1197829

**Comment by rosswbrown** [comment]
As mentioned above Other Database (ODBC) is not a part of the Tableau Connector SDK.  The documentation for that connector can be found at https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases.htm

**Comment by traceon** [comment]
As I clarified above, the question is more about the mechanics of how custom TDC values are applied, not asking about ODBC-specific stuff. All the available documentation doesn't answer the question.
