### ISSUE TITLE
require port field for connectors

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#442]
**About You:**
Name: Chris Clark
Company: Actian

Is there a way to require the port field be filled in? E.g. https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/connectionResolver.tdr#L8 indicates port is required but you can clear the field out in Tableau and it shows as "Optional".

I can't see anything in https://tableau.github.io/connector-plugin-sdk/docs/ui

Semi-related - is it possible to customize validation? Port field appears to restrict to numeric.

**Comment by pvanderknyff** [comment]
I don't think it's possible to make port required, unfortunately.

As for port, I think it's restricted to numeric by design, since it uses the same port widget as our other connectors. If you're trying to use it as another type of field, refer to my answer for your custom fields answer: https://github.com/tableau/connector-plugin-sdk/issues/443#issuecomment-573242711.

**Comment by jainam1995** [comment]
@clach04 
With the connection dialog v2 we now enable creating custom fields making them required and optional as required . The documentation for that is available here : https://tableau.github.io/connector-plugin-sdk/docs/mcd . Does this fix the issue ?
