### ISSUE TITLE
Tableau 2020.2 TDVT testing on MacOS

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#493]
**About You:**
Name: Bogdan Ghit
Company: Databricks Inc.

**Your question:**
I set up TDVT on MacOS using the same steps as on Windows and I wanted to test the embedded Databricks connector in Tableau 2020.2. I'm getting the error below:
```
Suite,Test Set,TDSName,TestName,TestPath,Passed,Closest Expected,Diff count,Test Case,Test Type,Process Output,Error Msg,Error Type,Query Time (ms),Generated SQL,Actual (100)tuples,Expected (100)tuples
databricks,StaplesConnectionTestdatabricks,Staples.databricks,staples_connection_test,/Users/bogdan.ghit/Workspace/dev/tableau/connector-plugin-sdk/tdvt/tdvt/exprtests/pretest/connection_tests/staples/setup.staples_connection_test.txt,False,0,0,,expression,,"LoadDatasource TableauException: Tableau doesn't recognize the data source type 'databricks'. It might not be available in this version of Tableau, or it might be a connector plugin that's not installed on this system.
```
Basically, no tests are running, so I don't have any logs to share except this TDVT output, which may mean there's a configuration error.

**Comment by lukewrites** [comment]
This bit of the error message is what I'd focus on to start:
> it might be a connector plugin that's not installed on this system
Can you double check that your plugin connector is in the correct location?

**Comment by bogdanghit** [comment]
Databricks is already incorporated with Tableau, so I don't need to set the plugin connector path. Doing so on Windows works fine, wondering why doesn't it work on Mac as well.

**Comment by bogdanghit** [comment]
Another question is how am I supposed to test a change that I make in our connector repo, say this: https://github.com/databricks/tableau-connector/pull/7? Won't this clash with the embedded connector? I tried for instance changing the class names in the connector files, but the plugin is still not loaded correctly.

**Comment by pvanderknyff** [comment]
Do you see Databricks listed as a connector when launching on Mac? I'm wondering if the difference in how the mac install files are organized is preventing tabquerycli from seeing the system plugins (which would mean that Tableau doesn't have the connector loaded when running TDVT and the tests will fail).

The connector files are contained in "/Applications/Tableau Desktop 2020.2.app/Contents/Frameworks/connectors" (path to the install directory may be different on your machine). If the problem is related to Mac's install structure, you could maybe add the following to your [datasources's ini file](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#ini-file-structure) for TDVT (should be something like databricks.ini):

`CommandLineOverride= -DConnectPluginsPath=/Applications/Tableau Desktop 2020.2.app/Contents/Frameworks/connectors`

**Comment by pvanderknyff** [comment]
To test your new changes, you can remove the libdatabricks.dylib file from the connectors file I posted above (back up before you do so). That will mean your new connector is the only one. I don't think this is neccesary, as long as you change the display name of your connector to something like "Databricks 2" so you can see it on the connector list as a separate entity.

However, the more likely cause of ti not loading is that Databricks in the repo does not have a [vendor information section](https://tableau.github.io/connector-plugin-sdk/docs/ui#connector-name-and-vendor-information). This is intended, since it is embedded in Tableau's installers and has a slightly different integration than most custom connectors. However, when loading it using the command line argument you will need to add it to pass the XSD validation for the manifest file when Tableau starts up. 

You need to add something like the following to your manifest.xml file locally (but it's not something you push to the repo):
`<connector-plugin class='postgres_odbc' superclass='odbc' plugin-version='0.0.0' name='PostgreSQL ODBC' version='18.1'>
  <vendor-information>
      <company name="Company Name"/>
      <support-link url = "https://example.com"/>
  </vendor-information>
  ...
</connector-plugin>`

**Comment by bogdanghit** [comment]
Thanks for the detailed information @pvanderknyff. Indeed, removing the connector library and adding the vendor information fixed the issue.

**Comment by bogdanghit** [comment]
As for running TDVT on Mac, it still doesn't work even after setting the DConnectPluginsPath to the connector location. The connector is listed when launching on Mac.

**Comment by bogdanghit** [comment]
@pvanderknyff a short update:
1) Shading the embedded connector worked after removing the file as you suggested and adding the vendor info. The name it displays is something like "Databricks2 by Databricks". The company reference is not listed on the embedded connector though.
2) Running TDVT against a plugin connector on MAC now partially works but some tests fail with the following error:
`Attempting to run query...
DataSourceException: No such column [customername].

DataSourceException: No such column [customername].

DataSourceException: No such column [customername].

DataSourceException: No such column [customername].

DataSourceException: No such column [customername].

DataSourceException: No such column [marketsegment].

TableauException: Tableau cannot evaluate the query that results from this calculation.

Error running query
`
The INI file I use has the following configuration:
`
[Datasource]
Name = databricks2

CommandLineOverride = -DConnectPluginsPath=/Users/bogdan.ghit/Workspace/dev/tableau/connector

MaxThread = 1

LogicalQueryFormat = tableau_tdvt

[LogicalConfig]
Name = tableau_tdvt
tablename = $dsName
tablePrefix = [tableau_tdvt].
tablenameUpper = True
tablenameLower = True
bool_underscore = True
fieldnameDate_underscore = True
fieldnameLower = True
fieldnameUpper = True
fieldnameNoSpace = True
fieldnameLower_underscore = True
fieldnameUnderscoreNotSpace = True

[ConnectionTests]
CastCalcsTestEnabled = True
StaplesTestEnabled = True

[StandardTests]

[LODTests]
`

**Comment by pvanderknyff** [comment]
1. The company name is expected, for 3rd-party custom connectors being loaded we differentiate them from built-in connectors. The built-in Databricks does not have this because we hardcode an exception for built-in connectors, but to load the in-development version of it you need to follow the same rules as the 3rd-party connectors. 

(Also, if you have a separate class name and display name you technically don't have to remove the built-in connector library since it will just show both)

2. Is this a Mac-only failure? Does the same connector (ie the databricks2 one, not the embedded one) pass on Windows when connecting to the same table? It looks like a  logical query problem, but that in theory would fail on both places, which is throwing me off a bit. 

If you connect in Tableau Desktop to the table, can you see the customername table? (I'm guessing this is the staples data source). 

3. You do not need to re-generate the .tds file.

**Comment by sidwray** [comment]
tfs 1197806
