### ISSUE TITLE
Connector plugins are not working with Tableau Server

### ISSUE THREAD

**Issue by ksr3579** [tableau/connector-plugin-sdk#51]
I am following the same steps as given in the document to achieve connector in tableau server, but i'm getting below error. Please suggest

 C:\Users\Administrator>tsm configuration set -k native_api.connect_plugins_path -v C:/tableau_connectors
Logging in as user 'Workstation\Administrator' since no --username flag was given.
Password:
Configuration error: At least one configuration value you specified does not match a known configuration key. This applies to the following keys: '[native_api.connect_plugins_path]'

Use this parameter to override unknown key error: --force-keys

**Comment by dcory** [comment]
Are you using 2019.1 Beta 2?

**Comment by gmoin789** [comment]
Yes, Tableau Server 2019.1 Beat 2.

**Comment by ksr3579** [comment]
Any update for me on the above issue?

**Comment by pvanderknyff** [comment]
Thank you for your patience. Right now, native_api.connect_plugins_path is not listed as a "known configuration", but it does work. Adding --force-keys to the end of the command will bypass the check and add the configuration key as intended:
`tsm configuration set -k native_api.connect_plugins_path -v C:/tableau_connectors --force-keys`

Once the changes are applied and the server is restarted, any valid plugins in the folder specified should appear in the connectors list.

Let me know if the plugins still do not appear after using --force-keys.

**Comment by ksr3579** [comment]
Thanks for your help & It worked after using the --force-keys. Now i'm able to publish the connector workbooks.
But I can't able to see my connector on Tableau server list of connector & also i can't able to see some of my peers, Can you please help me how can i see my connector on Tableau Server connectors list.

**Comment by lriggs** [comment]
Web Authoring (creating a new connection from the web) is not currently available for all connector superclasses.  I apologize for the confusion and have updated our documentation to mention this.

If your connector is based on 'odbc' or 'jdbc,' then you can publish your workbook or datasource from desktop to server, but you can't create a new connection directly on server. Connectors based on 'mysql_odbc' do support web authoring because this ability is inherited from the mysql code they are based on.
