### ISSUE TITLE
TDVT - Logical Query Config and Schema

### ISSUE THREAD

**Issue by ocientdmurphy** [tableau/connector-plugin-sdk#512]
**About You:**
Name: Dylan Murphy
Company: Ocient

**Your question:**
I'm running the tdvt tool against a custom connector that we built for our database. I notice in the documentation that it says that in the staples tds file, it should have a relation connection to calcs. The only relation entry in mine is 

relation connection='leaf' name='staples' table='[tableau].[staples]' type='table' /

I don't see a logical config for my schema, so I selected admin_lower. I ended up progressing and ran the test tool. 

In the output of the test tool logs, I see the following messages. I assume they're coming from me selecting admin?

**2020-05-15 14:19:48,416 Thread-[2] Command line output:Attempting to run query...
TableauException: No such table: [admin].[Staples]

Error running query**

However, when I look in the log of our server, it looks like it's using the right schema. I see a bunch of valid errors, like this

**[2020-05-15T18:04:06.498805][DEBUG][role169] cmdComp::Connection: SQL text is: SELECT CAST( FLOOR(EXTRACT(EPOCH FROM CAST((CAST('1900-01-01 00:00:00' AS TIMESTAMP) + NULL * INTERVAL '1 DAY') AS TIMESTAMP)) / 3600) - FLOOR(EXTRACT(EPOCH FROM CAST((CAST('1900-01-01 00:00:00' AS TIMESTAMP) + NULL * INTERVAL '1 DAY') AS TIMESTAMP)) / 3600) AS BIGINT) AS "TEMP(Test)(4062119106)(0)"
FROM "tableau"."calcs" "calcs"
HAVING (COUNT(1) > 0)
[2020-05-15T18:04:06.499323][ INFO][role169] cmdCompServer: ParseCancellationException: no viable alternative at input 'floor(extract(epochfromcast((cast('1900-01-01 00:00:00'astimestamp)+null*interval'1 DAY''**

So, I know the test tool is hitting the database. It also looks like the query is using the correct schema in the SQL that hits the db. 

Questions - 

Do I need to worry about or adjust to what I'm seeing in the staples tds file (no calcs relation)?
Do I need to worry about or adjust to having a logical query config that matches my schema?
Do I need to worry about or adjust to the error messages in the tdvt file (can't find admin.staples)?

**Comment by pvanderknyff** [comment]
I'm confused as to why your TDVT is working with calcs but not staples. admin_lower should be looking for staples with a lowercase s, but the error is for one with a capital one. Plus, the prefix is "tableau", not "admin", yet calcs seems to be hitting correctly, when admin_lower would . Can you confirm that the TDVT results have all the Staples tests failing with the no table found error, while the Calcs tests are passing or failing with other errors, and check the generated sql to see what excat table TDVT is trying to connect to?? If the logical query config is incorrect I would expect all tests to fail. 

You may need to make your own logical query config, the [ini file example](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#ini-file-structure) has some details on that.

If you haven't seen it, a good resource to investigate TDVT failures is the Tableau workbook [here](https://github.com/tableau/connector-plugin-sdk/blob/master/tdvt/TDVT%20Results.twbx).

To answer your questions at the end in more detail:
1) The name of the table in the relation should be the name of the table you're connecting to, your staples tds will not have a calcs relation because calcs is another table. You will find the calcs relation in your cast_cals tds file. I looked at our docs, and there is a typo where we direct people to Staples and then use the cals relation as an example instead of the correct Staples one. I'm legitimately gobsmacked how no one has called us out on that yet, I'll get it fixed.
In the end, it doesn't really matter, you just need to match the casing and such. Basically cacls and staples are interchangeable for the purposes of logical query config.

2) Yes, the logical query needs to match your schema so TDVT can issue queries against the correct table. If it's wrong you'll see the "No such table" error.
3) You mention that the error appears in the "output of the test tool logs". I'm not 100% sure what you mean by that. If it's the process output column in test_results_combined.csv file, that can be misleading, as it may be from an earlier test that failed. The "Error Msg" column is more reliable to make sure that the error actually belongs to that test case. You can also see the expected/actual tuples, and the sql we generated.

**Comment by ocientdmurphy** [comment]
Thanks so much for the help!

1) OK, one less problem on my end :) I thought that might've been the case.

2) I renamed my schema in the database to admin. I believe this helped with calcs. I'm now getting more tests passing. 

3) I was looking at the output of the tdvt_log_combined.txt file. 

It appears that it still isn't finding the Staples table at all. I tried renaming the staples data file to lowercase s. I'll try a few more things tomorrow. It's odd though that using admin_lower, it still appears to want to find the uppercase Staples file. I'll follow up with more information.

**Comment by ocientdmurphy** [comment]
OK, I tried a couple different things. I was able to continue using admin_lower and get the staples tests to run. It does in fact want an uppercase Staples. Once I changed the name of the table in the database and the .tds file, it seemed to work. 

However, I ended up trying to create my own Logical Config anyway. Our database doesn't support spaces in the column names. I wanted to use the fieldnameUnderscoreNotSpaces = True to account for this. There are underscores in the spaces of the column names in the database. I'm attaching the .ini file. 

I recreated the workspace multiple times, and I keep hitting this same problem using my own Logical Config. Is there something else I need to set or change when using my own logical config?

Dylans-MacBook-Pro:tdvt_workspace dylanmurphy$ tdvt run mydb --generate
Generating test files from: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/generate/input/lod
Writing test files to: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/setup/lod
Generating test files from: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/generate/input/staples
Writing test files to: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/setup/staples
Generating test files from: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/generate/input/calcs
Writing test files to: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/setup/calcs
Generating test files from: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/generate/input/union
Writing test files to: /Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt/logicaltests/setup/union
Done: 23.334814071655273
Setting tdvt thread count to: 1
Testing mydb
No tests found for config [name=logical.calcs.mydb] [tds=cast_calcs.mydb.tds] [exclusions=] [test pattern=logicaltests/setup/calcs/setup.*.admin.xml] [is_logical=True] [root_dir=/Users/dylanmurphy/Documents/Tableau Work/connector-plugin-sdk-master/tdvt/tdvt]
No tests found. Check arguments.

[mydb copy.ini.txt](https://github.com/tableau/connector-plugin-sdk/files/4663657/mydb.copy.ini.txt)

**Comment by pvanderknyff** [comment]
You named the logical config "admin", but there is already one called "ADMIN". I'm not 100% sure if it's case sensitive, but maybe try renaming to config to something like mydb_logical_query and see if that works.

**Comment by ocientdmurphy** [comment]
Turns out that it isn't case sensitive :) I think that I'm in business. Thank You!
