### ISSUE TITLE
Connector rewrite ISNULL to NVL

### ISSUE THREAD

**Issue by JhusiJeremy** [tableau/connector-plugin-sdk#653]
**About You:**
Name: Weihong Lou
Company: Kyligence

**Your question:**
Hi Tableau Team,

After we switch from odbc + tdc to connector, we find out that connector rewrites
    A = B or (A is null and B is null)
to
    (NVL(A, '0') = NVL(B, '0')) and (NVL(A, '1') = NVL(B, '1'))

The full sqls are shown below. The rewrite happens in `join... on` condition.
odbc + tdc
```
SELECT SUM(("t0"."X_measure__0" + "KYLIN_SALES"."ITEM_COUNT")) AS "usr_Calculation_340303290123309057_ok" 
FROM "DEFAULT"."KYLIN_SALES" "KYLIN_SALES"   INNER JOIN (   
	SELECT "KYLIN_SALES"."OPS_REGION" AS "OPS_REGION"
	,     SUM("KYLIN_SALES"."PRICE") AS "X_measure__0"   
	FROM "DEFAULT"."KYLIN_SALES" "KYLIN_SALES"   
	GROUP BY "KYLIN_SALES"."OPS_REGION" ) "t0" 
ON (("KYLIN_SALES"."OPS_REGION" = "t0"."OPS_REGION") OR (("KYLIN_SALES"."OPS_REGION" IS NULL) AND ("t0"."OPS_REGION" IS NULL))) GROUP BY 1.1000000000000001
```

connector
```
SELECT SUM(("t0"."X_measure__0" + "KYLIN_SALES"."ITEM_COUNT")) AS "usr_Calculation_340303290122227"
FROM "DEFAULT"."KYLIN_SALES" "KYLIN_SALES"
  INNER JOIN (
  SELECT "KYLIN_SALES"."OPS_REGION" AS "OPS_REGION",
    SUM("KYLIN_SALES"."PRICE") AS "X_measure__0"
  FROM "DEFAULT"."KYLIN_SALES" "KYLIN_SALES"
  GROUP BY "KYLIN_SALES"."OPS_REGION"
) "t0" ON ((NVL("KYLIN_SALES"."OPS_REGION", '0') = NVL("t0"."OPS_REGION", '0')) AND (NVL("KYLIN_SALES"."OPS_REGION", '1') = NVL("t0"."OPS_REGION", '1')))
GROUP BY 1.1000000000000001
```

We have implemented ISNULL function in our dialect. The dialect and manifest files are
 attached. How can I prevent the rewrite? Look forward to your reply. Thanks!

Weihong

[dialect.tdd.txt](https://github.com/tableau/connector-plugin-sdk/files/5544372/dialect.tdd.txt)
[manifest.xml.txt](https://github.com/tableau/connector-plugin-sdk/files/5544373/manifest.xml.txt)

**Comment by saugatt** [comment]
Hi Weihong, it turns the issue with rewriting ISNULL to NVL is occurring because of using `ProgressOpenEdgeDialect` as the base dialect. This base dialect has null handling specific to Progress OpenEdge which is being reflected in the generated query for your connector. The [documentation ](https://tableau.github.io/connector-plugin-sdk/docs/design)suggests only using an existing dialect as a base if "your database follows the SQL standards of another database that Tableau already supports". I would suggest working with one of the[ sample dialects ](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/) without a base and making modifications from there. This should solve this issue.

**Comment by JhusiJeremy** [comment]
Got it. Thanks!.

Weihong

**Comment by JhusiJeremy** [comment]
@saugatt When I switch from ProgressOpenEdgeDialect to Hive12Dialect without touching anything else, then run tdvt test on windows, an UnicodeDecodeError happens.

![image](https://user-images.githubusercontent.com/9805908/99519090-5de09a80-29cc-11eb-8de9-798c7502f3bd.png)

![image](https://user-images.githubusercontent.com/9805908/99519450-dba4a600-29cc-11eb-83b2-ec569cc6fb94.png)

When I switch back to ProgressOpenEdgeDialect, tdvt test can run again. There is not much info I can get from the erro stack trace.

**Comment by saugatt** [comment]
Could you check if there are non-English characters in the folder path were the TDVT environment or comments in the config files?
