### ISSUE TITLE
JavaScript globals allowed in the connection builder

### ISSUE THREAD

**Issue by bogdanghit** [tableau/connector-plugin-sdk#66]
What is the supported set of javascript globals that we can use in the connection builder? Is it possible to create other dialogs and make REST API calls from this script?

**Comment by bogdanghit** [comment]
When i set a wrong server address or in general if the connection details are wrong, there is a pop-up window displaying that an error occurred while communicating with the server. How can I customize and generate such a window with the SDK?

**Comment by lriggs** [comment]
Hi Bogdan, can you elaborate on your use case for popping up a window? What would you like it to contain?

The JavaScript engine is very limited by design. It is currently intended just for local evaluation of certain functions and is far more constrained than the engine we use for our WDC connectors. Can you tell us a little more about the type of connector you would like to write?

**Comment by bogdanghit** [comment]
Thanks for your reply! There are a few things I'd like to do in this connector such as:
1) make REST API calls and then populate a drop-down menu with the results
2) pop up a window with an error message if some parameter value is not allowed
3) embed a logo in the connection dialog window
4) add extra fields to the connection dialog with extra ODBC driver parameters that can be appended in the connectionBuilder.js to the connection string.

Are any of this things possible with the current SDK?

**Comment by lriggs** [comment]
Tracking these enhancements internally.
