### ISSUE TITLE
[BUG] Test failures -- LocalException for federated connections

### ISSUE THREAD

**Issue by waraposn** [tableau/connector-plugin-sdk#710]
**Describe the bug**
Out of 841 tests, there's 99 tests failing with "LocalException: Cannot check capabilities of a federated connection." We worked with @lukewrites to debug the issue and he will send over the logs + latest connector files 

**Screenshots**
<img width="1501" alt="TestFailure" src="https://user-images.githubusercontent.com/47156058/106969610-ff3fd880-66ff-11eb-92ac-cf0cc92531d8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Tableau Version: Desktop 2020.4

**About you:**
 Name: Neeraj Soparawala
 Company: Starburst Data

**Comment by lukewrites** [comment]
Logs & connector are in our SDK slack channel.

**Comment by rosswbrown** [comment]
Hi,
This error is likely occurring because the `.tds` files supplied to [TDVT](https://tableau.github.io/connector-plugin-sdk/docs/tdvt) have not been prepared as expected.  Please see the [Test a new data source](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#test-a-new-data-source) section of the documentation for the full steps on creating a new `.tds` file for TDVT.

The [About your test suite](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#about-your-test-suite) section describes the changes you should be able to observe in the `.tds` file after running the `add_ds` command.
> This occurs in two places, \<named-connection name='leaf'\> and \<relation connection='leaf' \>. If this is not done, the logical query tests might cause tabquery crashes or application exceptions.

Thanks,
Ross
