### ISSUE TITLE
Custom connector not loading in Tableau Desktop 2020.4

### ISSUE THREAD

**Issue by pshrivas** [tableau/connector-plugin-sdk#734]
**About You:**
Name: Prateek Shrivastava
Company: Dremio

**Your question:**
I built a new custom connector - Trying the snowflake oauth example here - https://github.com/tableau/connector-plugin-sdk/tree/dev-2021.1/samples/scenarios/snowflake_oauth

Next - Followed steps here [Signing example](https://tableau.github.io/connector-plugin-sdk/docs/package-sign) the connector.
I followed Step 1.1 and Step 1.2.
Skipped STEP 2.
Completed STEP 3.

Once it was self-signed, I moved the connector inside the right folder in my mac ("My Tableau Repository -> Connectors").

Problem: When I relaunch the Tableau Desktop, It doesn't load the 'snowflake_oauth' connector which I just built.

Question: Why is it so? Do I have to get the jar signed by CA (STEP 2) ?

**Comment by sidwray** [comment]
Correct, Tableau does not support self signed certs today.   For the final packaging step, and CA is required.

**Comment by pvanderknyff** [comment]
Hi Prateek:
There are two reasons why this connector will not work in 2020.4:

First, as Sid mentioned, Tableau does not support self-signed certs, so ultimately you will need to get it signed by a CA. However, when testing the taco, you can disable verification using the `-DDisableVerifyConnectorPluginSignature=true` command line argument when launching Tableau. More details on running connectors, including loading an unpackaged connector, are [here](https://tableau.github.io/connector-plugin-sdk/docs/run-taco).

However, I don't think that's the reason why the connector is not being loaded in 2020.4. If the signature is not valid, it will still appear in the connector list, but will throw an error when you try to sign in.

The reason why the connector is being rejected is because OAuth is not supported in 2020.4. OAuth in the Connector SDK is being added in 2021.1 (the sample you're working off of is in the dev-2021.1 branch). When you package the connector using the OAuth feature, it will no longer work in earlier versions.

**Comment by pshrivas** [comment]
Got it..Thanks pvanderknyff
