### ISSUE TITLE
Hive Example with SSL

### ISSUE THREAD

**Issue by kgm789** [tableau/connector-plugin-sdk#74]
Hi

Can you please provide sample plugin with Hive authentication mode using SSL. Thanks

**Comment by lriggs** [comment]
Hi, Can you provide more information about what you would like to do? If you want behavior that is mostly similar to our existing Cloudera or Hortonworks connector you might be able to start with one of those as your base class even though our documentation does not recommend it since we haven't tested it. 'hortonworkshadoophive' is one option. This method would give you the connection dialog and all the connection builder code. You could just customize the connector name, driver, and dialect if needed.
