### ISSUE TITLE
TDVT tests - All logical tests fail

### ISSUE THREAD

**Issue by guanghwu** [tableau/connector-plugin-sdk#742]
**About You:**
Name: Guang

**Your question:**
For all the logical tests I am getting
```
Attempting to run query...
TableauException: Tableau cannot evaluate the query that results from this calculation.

Error running query
```
I think only one of the tests is running and the others don't run since the first one is failing.

From the logs I can see that the query is generated and I can manually run that query successfully in the database:
<img width="181" alt="result_in_db" src="https://user-images.githubusercontent.com/80545938/110992163-8c9bcb80-8343-11eb-8240-dec39a9c9c65.png">

Logs:
[logs.zip](https://github.com/tableau/connector-plugin-sdk/files/6132664/logs.zip)

Any advise?

**Comment by erademacher** [comment]
Hi Guang,

Typically, when you see that particular error message, it means the dialect doesn't define the minimum set of functions Tableau needs to evaluate the expression in the test. $IN_SET$ is an internal system function, and relies on type conversions defined in the dialect. In this case, it's likely that your dialect doesn't define conversion functions between string and datetime.

In case you haven't already, I'd strongly recommend starting with something like [this example dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/dialect.tdd) and modifying it as necessary, instead of trying to start from scratch or using a base dialect (which is really only for connectors that very closely match an existing native connector). That way at least all of the required components are in place.

If you need any further assistance with this, please attach your .tdd file.

Evan
