### ISSUE TITLE
OAuth - Question about refresh tokens and authorization server requirements

### ISSUE THREAD

**Issue by tifflhl** [tableau/connector-plugin-sdk#765]
**About You:**
Name: Tiffany Lam
Company: Dremio

**Your question:**
Hi All, wondering if refresh tokens are required for all Tableau distributions when using the OAuth authentication mode? Moreover, can I assume that Tableau Connector SDK Oauth will work with any standard [OAuth 2.0](https://tools.ietf.org/html/rfc6749) authorization server? If not, are there specifications?

**Comment by wangxinlei** [comment]
Hey Tiffany,
Currently refresh tokens are required for pluggable OAuth, there are some native oauth connector that do not issue refresh token and we handle them specially. We can revisit this if you can justify your usecase and we'll evaluate that.
You should be able to follow most part of standard OAuth 2.0 spec, one important thing is we are only using the Auth Code Grant flow.

**Comment by tifflhl** [comment]
Hi Eric,

Thanks for the response, I have a couple follow-up questions:
- Does Tableau make separate requests for access tokens and refresh token? For instance, if the authorization server always return access token and refresh token in the same response, would it work with Tableau?
- Does Tableau create a new connection every time after the access token is refreshed? Opening new connections is costly for the driver and the server, so we would like to understand if more rigorous connection management is required in our JDBC driver.
- Are ID tokens required?

**Comment by wangxinlei** [comment]
Hey Tiffany:
Tableau always make a single request to get both refresh Tokens and access Token.
If the driver throws exception while processing the query yeah we'll have to re-connect. This normally would not be a concern since for a single desktop/server editing session it's unlikely your accessToken expires. When you are in a viewing session we'll refresh the token first before doing the actual connecting.
ID Tokens are not required, but you need to have a way to pass back the username, it can either be in the response map for tokens, or you provide a separate userInfo endpoint to retrieve username.

**Comment by xsgao-github** [comment]
3.5 years later, anyone knows if this has changed or not?
