### ISSUE TITLE
Connector rewrite NULL to CAST(NULL AS CHAR)

### ISSUE THREAD

**Issue by JhusiJeremy** [tableau/connector-plugin-sdk#769]
**About You:**
Name: Weihong Lou
Company: Kyligence

**Your question:**
Hi tableau team,

We already know that the connector will rewrite ISNULL to NVL function. But it also cast null to char type during the rewrite, e.g., `NVL("KYLIN_SALES"."ITEM_COUNT",CAST(NULL AS CHAR)) IS NULL`. Our data source uses Calcite to analyze the sql. Calcite NVL function does not accept two values with different types. So if the first param is not in char type, an error happens:

![image](https://user-images.githubusercontent.com/9805908/114852126-13e1d080-9e15-11eb-832c-c309660cc5bf.png)

This happens when we try to have an expression: `MAX([Item Count],[Price])` . [Item Count] is Integer and [Price] is decimal.

![image](https://user-images.githubusercontent.com/9805908/114853204-24467b00-9e16-11eb-8db1-d8ca454285d7.png)
![image](https://user-images.githubusercontent.com/9805908/114853220-26a8d500-9e16-11eb-9fd2-ecf3fcfd2697.png)

Then the connector shoots out a sql like:

`SELECT SUM((CASE
	WHEN (NVL("KYLIN_SALES"."ITEM_COUNT",CAST(NULL AS CHAR)) IS NULL) OR (NVL("KYLIN_SALES"."PRICE",CAST(NULL AS CHAR)) IS NULL) THEN CAST(NULL AS FLOAT)
	WHEN "KYLIN_SALES"."ITEM_COUNT" > "KYLIN_SALES"."PRICE" THEN "KYLIN_SALES"."ITEM_COUNT"
	ELSE "KYLIN_SALES"."PRICE" END)) AS "sum_Calculation_172713048896309"
FROM "DEFAULT"."KYLIN_SALES" "KYLIN_SALES"
GROUP BY 1.1000000000000001`

There is one NVL which takes [ITEM_COUNT] and null in type char as input, and another NVL which takes [PRICE] and null in type char as input.
Is there any way that we can control the type that null is cast into, so that we can keep the types of two params of NVL to the same?

Our dailect.tdd file is attached. We do not override any ISNULL or NVL functions.
[dialect.txt](https://github.com/tableau/connector-plugin-sdk/files/6317007/dialect.txt)

Look forward to hear from you.

Thanks!

Weihong

**Comment by jainam1995** [comment]
Tracking internally. Id : 1256407

**Comment by saugatt** [comment]
Hi Weihong, here we are casting the second argument to CHAR because of the limitation in the OpenEdge database and since your connector is using  `ProgressOpenEdgeDialect` as the base dialect, it is generating the NVL function with CAST as char. This base dialect has null handling specific to Progress OpenEdge which is being reflected in the generated query for your connector.  The only way to overcome this would be to write the dialect file with a different base class and no base class at all. You could check [SQLDialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd) and [Postgre Dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/dialect.tdd) as a starting point.  This was the possible problem with how we handle nulls in OpenEdge in #653
