### ISSUE TITLE
[BUG] Certain OAuth authentication errors are non-descriptive

### ISSUE THREAD

**Issue by alismess-db** [tableau/connector-plugin-sdk#790]
**Describe the bug**
If the user enters an invalid URL as the instanceUrl (e.g. missing https://, or otherwise invalid like `abcdefgh`), then the resulting error message is "No details available". However, the OAuth logs do have more information, like `java.net.MalformedURLException ...`. It would be preferable to return this to the user.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Tableau Version: 2021.1.1

**About you:**
 Name: Ali Smesseim
 Company: Databricks

**Comment by jainam1995** [comment]
Internal tracking id : 1268956

**Comment by wangxinlei** [comment]
I think this is fixed in the latest 2020.3 release.
We'll show the following screen if your have set your `instanceUrlValidationRegex`.
![image](https://user-images.githubusercontent.com/9013189/123462469-3889bf80-d59f-11eb-9e93-8105f7a2e5f8.png)
And we'll show the exception message if you have not set that field like this:
![image](https://user-images.githubusercontent.com/9013189/123462874-b4840780-d59f-11eb-9ea2-e38e5d5947e4.png)
