### ISSUE TITLE
Failed to get CSR signed by certification authority

### ISSUE THREAD

**Issue by WuYR123** [tableau/connector-plugin-sdk#825]
**About You:**
Name:WuYR123
Company:

**Your question:**
Question 1.According to document https://tableau.github.io/connector-plugin-sdk/docs/package-sign,signature failed.
![image](https://user-images.githubusercontent.com/87626601/126758497-c3b77c24-8a53-43d4-9608-726d06c33c68.png)
Signature failed, as shown in the figure：
![image](https://user-images.githubusercontent.com/87626601/126759170-2769e0ae-ee8b-4f24-9802-afa7c9602d45.png)
Before reporting an error, I did the following according to the document: Step 1
![image](https://user-images.githubusercontent.com/87626601/126759413-1be6da72-68df-43c9-b240-6feb717204a0.png)
Step 2
![image](https://user-images.githubusercontent.com/87626601/126759627-212eb70d-4451-468d-8d4a-e6e3a878d39a.png)
Step 3
![image](https://user-images.githubusercontent.com/87626601/126759800-00825864-8238-422d-a36a-fdc3a0285113.png)
Question 2.If double-click staples.pgodbc.tds, an error will be reported:
![image](https://user-images.githubusercontent.com/87626601/126761088-adb9fcf3-4a6e-4a63-9ddd-b71650ba7895.png)

**Comment by pvanderknyff** [comment]
Unfortunately, I can't understand the Tableau error message in question 2, can you switch Tableau to English for the error? If it's something similar to `Signature Verification Failed`, then it's expected as the taco is not signed. To skip the signature verification step, you can follow the steps [here](https://tableau.github.io/connector-plugin-sdk/docs/run-taco#disabling-signature-verification).

For Question 1, I can't understand the error messages there either, but given the commands you're running it looks like you're trying to import a self-signed cert into the java keystore. That's not a supported path for Tableau connectors, because we expect the final .taco file to run on any machine without needing the customer to manually import the cert. You need to get the certificate signed by a trusted certificate authority that is trusted by default by Java. (If I'm mistaken about my reading of the situation and you are already working with a certificate authority, you should go to them for support on these steps.)

**Comment by pvanderknyff** [comment]
Closing issue. Please re-open if you're still seeing this issue.
