### ISSUE TITLE
How can I unquote database identifiers and use the database name instead of the schema name for generated SQL?

### ISSUE THREAD

**Issue by CassidyMountjoy** [tableau/connector-plugin-sdk#859]
**About You:**
Name: Cassidy Mountjoy
Company: Blockpoint Systems

**Your question:**
I'm building a custom connector using a JDBC, which I'm building as well. When adding columns to my sheet, I'm getting the unexpected SQL:

_SELECT "batters"."ab" AS "ab"
FROM "schema_name"."batters" "batters"
GROUP BY "batters"."ab"_

1.) I would like unquoted identifiers. In the JDBC there is  a method that looks like it would be the ticket to unquoted idents, **getIdentifierQuoutString()** that:

Retrieves the string used to quote SQL identifiers. This method returns a space " " if identifier quoting is not supported

My JDBC returns a space " ".

2.) I would like to use the database name instead of the schema name. To my knowledge, I would think this would be specified in the **connectionMetadata.xml** file, which has schemas disabled:

\<connection-metadata>
\<database enabled='true'>
\<field />
\</database>
\<schema enabled='false' />
\</connection-metadata>

Am I missing something here?

**Comment by rosswbrown** [comment]
To the first question, the quote string is defined as a part of the connector [dialect](https://tableau.github.io/connector-plugin-sdk/docs/dialect). I believe the `id-quotes` allows customization in general ([sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd#L256)), but I'm not sure if empty string has been explicitly tested, so you'll want to test it to confirm.  

Somewhat related, there are additional customizations to the identifier mangling cases with: `id-allowed-characters`, `id-case`, and `id-max-length` ([sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Annotated.tdd#L1440), [XSD](https://github.com/tableau/connector-plugin-sdk/blob/master/validation/tdd_latest.xsd#L645))

For the second question, by design Tableau sends only `Schema.Table`, or just `Table` is Schema isn't supported, as a part of the queries.  There are more details on [Database Hierarchy](https://tableau.github.io/connector-plugin-sdk/docs/metadata-enumeration#catalog-hierachy) usage in the Metadata Enumeration doc page.

**Comment by CassidyMountjoy** [comment]
Thanks Ross, I was able to unquote the database identifiers by using an empty string for `id-quotes`.

I used the Metadata Enumeration to disable certain metadata features that aren't supported yet: indexes and foreign keys.

My queries are now running and I'm using tdvt to debug, thanks!
