### ISSUE TITLE
Is it possible to redefine some operators?

### ISSUE THREAD

**Issue by Yury-Fridlyand** [tableau/connector-plugin-sdk#890]
**Your question:**
I'm wondering whether it is possible to redefine some operators?
**1.** For example, TDVT test case `(if bool0 then int(bool1) else int(bool2) end) == int(true)` in test `setup.logical.bool.txt` fails, because the query has the following clause: `NOT 1`.
The SQL engine can't apply boolean functions to an integer, so query fails.
I tried adding these functions to the dialect, but both of them were ignored:
```xml
        <function group='cast' name='BOOL' return-type='bool'>
            <formula>IF(ISNULL(%1), NULL, IF(%1 &lt;&gt; 0, 1, 0))</formula>
            <argument type='int' />
        </function>

        <function group='operator' name='!' return-type='bool'>
            <formula>IF(ISNULL(%1), NULL, IF(%1 &lt;&gt; 0, 0, 1))</formula>
            <argument type='int' />
        </function>
```
How is it possible to make TDVT to process `int`s as `bool`s properly?
`CAP_QUERY_BOOLEXPR_TO_INTEXPR = no`
**2.** I tried to set this capability to `yes`. All test cases failed in this test - TDVT generates queries with `bool0 <> 0`. SQL engine can't process them.
I have these two functions in the dialect, but both are ignored:
```xml
        <function group='operator' name='!=' return-type='bool'>
            <formula>(%1 AND %2 = 0 OR NOT %1 AND %2 &lt;&gt; 0)</formula>
            <argument type='bool' />
            <argument type='int' />
        </function>
        <function group='operator' name='!=' return-type='bool'>
            <formula>(%1 = 0 AND %2 OR %1 &lt;&gt; 0 AND NOT %2)</formula>
            <argument type='int' />
            <argument type='bool' />
        </function>
```

What do I miss? Isn't there a bug?
Thank you!

**Comment by jie-d** [comment]
Internal tracking id: 1349238

**Comment by rosswbrown** [comment]
The best starting place to describe boolean support is [this section](https://tableau.github.io/connector-plugin-sdk/docs/dialect#boolean-support) of our dialect documentation.

`CAP_QUERY_BOOLEXPR_TO_INTEXPR = 'yes'` is mainly used if the underlying data source doesn't support boolean types at all. From [doc](https://tableau.github.io/connector-plugin-sdk/docs/capabilities):
>Set to ‘yes’ if data source does not support booleans natively in a result set. Set to ‘no’ if booleans are supported natively.

This tends to be uncommon though for modern data sources. I'll assume for the answer below that `CAP_QUERY_BOOLEXPR_TO_INTEXPR = 'no'`

To the specific question about the `(if bool0 then int(bool1) else int(bool2) end) == int(true)` test case, I'd recommend to start looking at these function definitions in the dialect:
```xml
    <function group='cast' name='INT' return-type='int'>
      <formula>(CASE
	WHEN %1 THEN 1
	WHEN NOT %1 THEN 0
	ELSE NULL END)</formula>
      <argument type='bool' />

    <function group='operator' name='==' return-type='bool'>
      <formula>(%1 = %2)</formula>
      <argument type='real' />
      <argument type='real' />
    </function>
```
The `formula` values above are from the reference postgres_jdbc [dialect](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/dialect.tdd) instead of what your connector requires.

For `group='operator'` functions, unless the `return-type='int'`, generally the `int` arguments are coerced into `real`.

**Comment by rosswbrown** [comment]
Feel free to reopen if this didn't answer your question, thanks.
