### ISSUE TITLE
Logical Tests Failing 

### ISSUE THREAD

**Issue by neosujoy** [tableau/connector-plugin-sdk#916]
Name: Sujoy Neogi
Company: Innominds

I am working on a Tableau connector, i see all logical and lod tests are failing, some of them were previously passing but now i see all are failing with "TableauException: Tableau cannot evaluate the query that results from this calculation."

For LOD tests i see "DataSourceException: No such function $IN_SET$ that takes arguments of type (int, datetime, datetime, datetime)."

Based on the forum posts it seems to be dialect issue, based on the postgres dialect if i have all the functions but not able to figure out, any other way to find the missing functions in dialect which i suppose is the reason behind this error

**Comment by neosujoy** [comment]
I upgraded to the latest tdvt, and defined the unsupported columns types in tds files. Now i see some test cases are fixed but i still see lot of errors like

DataSourceException: Abstract query SELECT [date0] is not defined.
DataSourceException: Abstract query SELECT [Order Date] is not defined.

Is there a way to fix these issues

**Comment by rosswbrown** [comment]
Hi. The two most common reasons errors like this may occur are an incomplete [dialect](https://tableau.github.io/connector-plugin-sdk/docs/dialect) or an incorrectly loaded TestV1 data set ([step 3](https://tableau.github.io/connector-plugin-sdk/docs/tdvt#set-up)).

Based on the error messages above I would suspect the dialect is the best starting point.  All of those errors look related to Date or DateTime type definition.  In addition to the Postgres [sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/dialect.tdd) we also have an additional folder of supplemental dialect examples [here](https://github.com/tableau/connector-plugin-sdk/tree/master/samples/components/dialects). It includes the [default](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/SQLDialect.tdd), a full `<function-map>` [list](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/FullFunctionMap.tdd) and a [complete example](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/dialects/Hive12Dialect.tdd) of a Hive-based data source dialect.

For a more detailed investigation we generally require these [artifacts](https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts).  Since this is a TDVT test the product logs and screenshots can be omitted. Thanks.

**Comment by neosujoy** [comment]
Thanks for the explanation, what i understand is the errors are coming because i have defined virtual/derived columns in the tds files, so the Staples Data, Calcs Data tests are passing as they are using the formulae to get the column values, but several tests like LOD are still sending select queries with the virtual column name for bool and datetime types, which are not supported by us, as these are not really present and only defined in tds file, the Abstract Query COLUMN is not defined error is coming, if TDVT is able to generate query for the Staples Data test case correctly i know nothing wrong with my column definition, this looks more of some tests cannot be run as column cannot be directly extracted.

**Comment by rosswbrown** [comment]
I'd recommend following the steps above for attaching artifacts. Even a single failing case's artifacts would be useful here. It is possible from the .tds files alone and the name of the test case we can identify the issue, but less likely.  Please remember to remove the PII from the .tds files before inclusion. Thanks.

**Comment by rosswbrown** [comment]
This can be reactivated when more details are provided.
