### ISSUE TITLE
Option to disable automatically generated grouping queries for large tables (or limiting it to avoid full table scan)

### ISSUE THREAD

**Issue by andiem-bq** [tableau/connector-plugin-sdk#980]
**About You:**
Name: Andie M

**Your question:**
We have a large data set that we connect to using [JDBC driver connector](https://exchange.tableau.com/products/605?version=2021.2). When working on worksheets w/ a live connection, Tableau sends the driver grouping or aggregation queries like SELECT column FROM table GROUP BY column or SELECT SUM(1) from table GROUP BY column. For this data set, queries that need to scan the entire table can take hours.

Expected behaviour for us would be to limit sampling to smaller amount of rows so we can work efficiently.

Are there any options to customize this behaviour through Tableau settings or the connector so that such queries are not sent or only a subset of the full table is used?

Here is example how to reproduce it:
1. Create a Table and populate it with large amount of data (e.g. >1TB).
2. Connect to the Database from Tableau
3. Drag and drop table 
4. Go to worksheet tab 
5. Drag a String column to the Rows area

Actual Result:
Tableau generated query (SELECT table.column FROM table GROUP BY table.column) which is expected to be slow and can take few hours to complete.

Expected Result:
Tableau skipped populating available values for the column, due to the large data set.

**Comment by joe-langford** [comment]
The closest thing Tableau has to this is "data source filters". You might give this a try if you haven't already. 

![image](https://user-images.githubusercontent.com/28787582/184973368-0d475f8c-2acf-428c-94bb-47d12adc9ab4.png)

One other possibility is to join the large table with a smaller "reference" table with the intent of putting a filter on the smaller table, thereby limiting the number of rows included in the SELECT that happens when you drag a column to the viz. For example suppose the large table had a column CITY, and you had a separate small table that only had cities; if you join these, then on the viz create a filter that selects only one city from the smaller table, when you drag a column of the larger table to the viz, the SELECT will only include rows for that one city; you can alter the filter later, after constructing your viz. 

Tableau does have on the backlog a feature to provide for an initial "prompt dialog" for filtering like this; it would be displayed when a table is initially dragged to the data pane. But that work is not yet scheduled.
